'''
Created on 2012-5-10
@author: lvchunhx
RESTFUL API
'''
RESTFUL_API_LAYERS = '/get/BBLAYERS'
RESTFUL_API_DISTRO = '/get/DISTRO'
RESTFUL_API_BB_NUMBER_THREADS = '/get/BB_NUMBER_THREADS'
RESTFUL_API_PARALLEL_MAKE = '/get/PARALLEL_MAKE'
RESTFUL_API_DOWNLOAD_DIRECTORY = '/get/DL_DIR'
RESTFUL_API_SSTATE_DIRECTORY = '/get/SSTATE_DIR'
RESTFUL_API_SSTATE_MIRROR = '/get/SSTATE_MIRROR'
RESTFUL_API_PACKING_FORMAT = '/get/PACKAGE_CLASSES'
RESTFUL_API_IMAGE_ROOTFS_SIZE = '/get/IMAGE_ROOTFS_EXTRA_SPACE'
RESTFUL_API_IMAGE_EXTRA_SIZE = '/get/IMAGE_ROOTFS_EXTRA_SPACE'
RESTFUL_API_BUILD_TOOLCHAIN = "/get/SDK_ARCH"
RESTFUL_API_NUMBER_THREADS = "/get/getCpuCount"
RESTFUL_API_DEPLOY_IMAGE_DIR = "/get/DEPLOY_DIR_IMAGE"
RESTFUL_API_INCOMPATIBLE_LICENSE = "/get/INCOMPATIBLE_LICENSE"
RESTFUL_API_SDKMACHINE = "/get/SDKMACHINE"
RESTFUL_API_COOKER_INIT = "/action/initcooker"
RESTFUL_API_COOKER_REST ="/action/resetcooker"
RESTFUL_API_CANCEL_BUILD_FORCE = "/action/forcecancelbuild"
RESTFUL_API_CANCEL_BUILD_UNFORCE = "/action/unforcecancelbuild"
RESTFUL_API_SYSTEM_CONFIG_REQUEST = "/action/asyncconfs"
RESTFUL_API_EVENT_QUEUE = "/action/getevents"
RESTFUL_API_PARSE_RECIPE = "/action/parserecipe"
RESTFUL_API_BUILD_PACKAGE = "/action/buildpkg"
RESTFUL_API_BUILD_IMAGE = "/action/buildimage"