#!/bin/sh
### BEGIN INIT INFO
# Provides:          Mixer setup
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initialize the audio mixer
# Description:       Restore mixer settings from asound.state
### END INIT INFO

# Author: Darren Hart <dvhart@linux.intel.com>
# Based on /etc/init.d/skeleton

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Audio mixer settings"
NAME=bbxm-audio
ALSACTL=`which alsactl`
SCRIPTNAME=/etc/init.d/$NAME

# Exit if amixer is not installed
[ -x "$ALSACTL" ] || exit 0

do_start() {
	$ALSACTL restore
}

do_stop() {
    $ALSACTL store
}

case "$1" in
start)
	echo "$NAME: setting default mixer settings."
	do_start
	;;
stop)
	echo "$NAME: saving mixer settings."
    do_stop
    ;;
*)
	echo "Usage: $SCRIPTNAME {start|stop}" >&2
	exit 3
	;;
esac

exit 0
