from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('',
     url(r'^index_dashboard/', 'hob.builds.views.index_dashboard'),
     url(r'^index/', 'hob.builds.views.index'),
     url(r'^parseRecipe_request/', 'hob.builds.views.parseRecipe_request'),
     url(r'^recipe_events/', 'hob.builds.views.recipe_events'),
     url(r'^createbuild_packagegroups/', 'hob.builds.views.createbuild_packagegroups'),
     url(r'^createbuild_recipes/', 'hob.builds.views.createbuild_recipes'),
     url(r'^search_recipe_dependencies/', 'hob.builds.views.search_recipe_dependencies'),
     url(r'^search_baseimage_dependencies/', 'hob.builds.views.search_baseimage_dependencies'),
     url(r'^createbuild_packages/', 'hob.builds.views.createbuild_packages'),
     url(r'^get_package_events/', 'hob.builds.views.get_package_events'),
     url(r'^createbuild_packages_list/', 'hob.builds.views.createbuild_packages_list'),
     url(r'^get_package_detail/', 'hob.builds.views.get_package_detail'),
     url(r'^search_package_dependencies/', 'hob.builds.views.search_package_dependencies'),
     url(r'^createbuild_buildimage/', 'hob.builds.views.createbuild_buildimage'),
     url(r'^get_image_events/', 'hob.builds.views.get_image_events'),
     url(r'^createbuild_buildimage_download/', 'hob.builds.views.createbuild_buildimage_download'),
     url(r'^getProgressBar/', 'hob.builds.views.getProgressBar'),
     url(r'^buildReports/', 'hob.builds.views.buildReports'),
     url(r'^shareBuilds/', 'hob.builds.views.shareBuilds'),
     url(r'^delete_builds/', 'hob.builds.views.delete_builds'),
     url(r'^builds_sort/', 'hob.builds.views.builds_sort'),
     url(r'^build_fast_package/', 'hob.builds.views.build_fast_package'),
     url(r'^build_fast_image/', 'hob.builds.views.build_fast_image'),
     url(r'^stop_building/', 'hob.builds.views.stop_building'),
     url(r'^cancel_buildings/', 'hob.builds.views.cancel_buildings'),
)