#!/bin/sh
### BEGIN INIT INFO
# Provides:          snb mixer setup
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initialize the snb audio mixer
# Description:       Unmute FRONT and set volume to ~70%.
### END INIT INFO

# Author: Darren Hart <dvhart@linux.intel.com>
# SNB changes are the fault of Tom Zanussi <tom.zanussi@intel.com>
# Based on /etc/init.d/skeleton

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Audio mixer settings"
NAME=snb-audio
AMIXER=`which amixer`
SCRIPTNAME=/etc/init.d/$NAME

# Exit if amixer is not installed
[ -x "$AMIXER" ] || exit 0

do_start() {
	$AMIXER set Front 36 > /dev/null
}

case "$1" in
start)
	echo "$NAME: setting default mixer settings."
	do_start
	;;
stop)
	;;
*)
	echo "Usage: $SCRIPTNAME {start|stop}" >&2
	exit 3
	;;
esac

exit 0
