from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('',
     url(r'^login/', 'hob.views.login'),
     url(r'^register/', 'hob.views.register'),
     url(r'^save_user/', 'hob.views.save_user'),
     url(r'^index/', 'hob.buildConfig.index'),
     url(r'^buildConfig_request/', 'hob.buildConfig.buildConfig_request'),
     url(r'^get_configEvents/', 'hob.buildConfig.get_configEvents'),
     url(r'^disp_advanceSettings/', 'hob.buildConfig.disp_advanceSettings'),
     url(r'^save_advanceSetting/', 'hob.buildConfig.save_advanceSetting'),
     url(r'^parseRecipe_request/', 'hob.recipe.parseRecipe_request'),
     url(r'^parseRecipe_event/', 'hob.recipe.parseRecipe_event'),
     url(r'^recipe_task_list/', 'hob.recipe_task_dependency.recipe_task_list'),
     url(r'^get_recipe_dependency/', 'hob.recipe_task_dependency.get_recipe_dependency'),
     url(r'^get_baseImage_dependency/', 'hob.recipe_task_dependency.get_baseImage_dependency'),
     url(r'^buildPackage_request/', 'hob.package.buildPackage_request'),
     url(r'^getPackage_event/', 'hob.package.getPackage_event'),
     url(r'^package_list/', 'hob.package.package_list'),
     url(r'^get_package_dependency/', 'hob.package.get_package_dependency'),
     url(r'^buildImage_request/', 'hob.image.buildImage_request'),
     url(r'^getImage_event/', 'hob.image.getImage_event'),
     url(r'^disp_image/', 'hob.image.disp_image'),
     url(r'^history_list/', 'hob.views.history_list'),
     url(r'^image_detail/', 'hob.views.image_detail'),
)