#!/bin/sh

# Poky Build Enviroment Setup Script
#
# Copyright (C) 2006-2007 OpenedHand Ltd.
# Copyright (C) 2010 Wind River Systems
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Identify the shell...
expr "$version" : '.*csh.*' > /dev/null && set CSH=csh || SH=sh

# If in csh, blank out all variables we might use...
[ -n "$CSH" ] && set SH=''
[ -n "$CSH" ] && set BASH_SOURCE=''

# Setup error processing
[ -n "$CSH" ] && set ERR=''

# It is assumed OEROOT is already defined when this is called
[ -z "$ERR" -a -n "$CSH" -a -z "$OEROOT" ] && set ERR="Error: OEROOT is not defined!"
[ -z "$ERR" -a -n "$SH"  -a -z "$OEROOT" ] && ERR="Error: OEROOT is not defined!"

# Setup BDIR
[ -z "$ERR" -a -n "$CSH" ] && set BDIR=''
[ -z "$ERR" -a -n "$SH"  ] && BDIR=''

[ -z "$ERR" -a -n "$CSH" -a -z "$BDIR" -a -n "$1" ] && set BDIR=`readlink -f $1`
[ -z "$ERR" -a -n "$SH"  -a -z "$BDIR" -a -n "$1" ] && BDIR=`readlink -f $1`

[ -z "$ERR" -a -n "$CSH" -a -z "$BDIR" ] && set BDIR="build"
[ -z "$ERR" -a -n "$SH"  -a -z "$BDIR" ] && BDIR="build"

[ -n "$CSH" ] && set BDIR_ABS=''
expr "$BDIR" : '/.*' > /dev/null && [ -n "$CSH" ] && set BDIR_ABS="abs"
expr "$BDIR" : '/.*' > /dev/null && [ -n "$SH"  ] && BDIR_ABS="abs"

[ -z "$ERR" -a -n "$CSH" -a -n "$BDIR_ABS" ] && setenv BUILDDIR "$BDIR"
[ -z "$ERR" -a -n "$SH"  -a -n "$BDIR_ABS" ] && export BUILDDIR="$BDIR"
[ -z "$ERR" -a -n "$CSH" -a -z "$BDIR_ABS" ] && setenv BUILDDIR "`pwd`/$BDIR"
[ -z "$ERR" -a -n "$SH"  -a -z "$BDIR_ABS" ] && export BUILDDIR="`pwd`/$BDIR"

unset BDIR_ABS
unset BDIR

[ -n "$CSH" -a "$?BBEXTRA" = "0" ] && set BBEXTRA=''
[ -z "$ERR" -a -n "$CSH" ] && set BITBAKEDIR="$OEROOT/bitbake$BBEXTRA/" 
[ -z "$ERR" -a -n "$SH"  ] && BITBAKEDIR="$OEROOT/bitbake$BBEXTRA/"

# Remove any symlinks from paths
[ -z "$ERR" -a -n "$CSH" ] && set BITBAKEDIR=`readlink -f "$BITBAKEDIR"`
[ -z "$ERR" -a -n "$SH"  ] && BITBAKEDIR=`readlink -f "$BITBAKEDIR"`

# Used by the poky-qemu script
[ -z "$ERR" -a -n "$CSH" ] && setenv BUILDDIR `readlink -f "$BUILDDIR"`
[ -z "$ERR" -a -n "$SH"  ] && export BUILDDIR=`readlink -f "$BUILDDIR"`

[ -z "$ERR" -a -n "$CSH" -a ! -d "$BITBAKEDIR" ] && set ERR="Error: The bitbake directory ($BITBAKEDIR) does not exist!  Did you source the script in the poky directory?"
[ -z "$ERR" -a -n "$SH"  -a ! -d "$BITBAKEDIR" ] && ERR="Error: The bitbake directory ($BITBAKEDIR) does not exist!  Did you source the script in the poky directory?"

[ -z "$ERR" -a -n "$CSH" ] && setenv PATH "${OEROOT}/scripts:$BITBAKEDIR/bin/:$PATH"
[ -z "$ERR" -a -n "$SH"  ] && export PATH="${OEROOT}/scripts:$BITBAKEDIR/bin/:$PATH"

unset BITBAKEDIR

# Stop multi byte characters breaking the patcher stuff - This is for Redhat / Fedora people really
[ -z "$ERR" -a -n "$CSH" ] && setenv LANG C 
[ -z "$ERR" -a -n "$SH"  ] && export LANG=C

[ -z "$ERR" -a -n "$CSH" ] && setenv BB_ENV_EXTRAWHITE "MACHINE DISTRO POKYMODE POKYLIBC http_proxy ftp_proxy https_proxy all_proxy ALL_PROXY no_proxy SSH_AGENT_PID SSH_AUTH_SOCK BB_SRCREV_POLICY SDKMACHINE BB_NUMBER_THREADS GIT_PROXY_COMMAND PSEUDO_DISABLED"
[ -z "$ERR" -a -n "$SH"  ] && export BB_ENV_EXTRAWHITE="MACHINE DISTRO POKYMODE POKYLIBC http_proxy ftp_proxy https_proxy all_proxy ALL_PROXY no_proxy SSH_AGENT_PID SSH_AUTH_SOCK BB_SRCREV_POLICY SDKMACHINE BB_NUMBER_THREADS GIT_PROXY_COMMAND PSEUDO_DISABLED"

[ -n "$ERR" ] && echo "$ERR"
unset ERR
